name = "indramayuowr1"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[[routes]]
pattern = "sakinahmawaddahwarahmah.my.id"
custom_domain = true
[vars]
# PROXYIP = "172.232.239.151:587"
UUID = "7188274e-e9b4-4842-b163-f7f4085c3f9f"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
